on:
  push:
    branches:
      - main # or your main branch name
  schedule:
    - cron: '0 */5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Tor Hidden Service
      uses: anuragmuxui/deploy-tor-action@v1
      with:
        repository: ${{ github.repository }}
